CREATE TABLE DADO_PESSOAL(
    ID NUMBER, TIPO VARCHAR2(50) NOT NULL,
    NOME_COMPLETO VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO VARCHAR(20) NOT NULL,
    SEXO VARCHAR2(50) NOT NULL,
    TELEFONE VARCHAR2(100) NOT NULL,
    CELULAR VARCHAR2(100) NOT NULL,
    CIDADE VARCHAR2(100) NOT NULL,
    BAIRRO VARCHAR2(100) NOT NULL,
    CEP VARCHAR2(100) NOT NULL,
    COMPLEMENTO VARCHAR2(100) NOT NULL,
    UF VARCHAR2(50) NOT NULL,
    URLFOTO VARCHAR2(100) NOT NULL,
    DATA_CADASTRO VARCHAR(20) NOT NULL,
    CONSTRAINT CH_P PRIMARY KEY (ID)
);

CREATE TABLE OPERADOR_CAIXA(
    ID NUMBER,
    DADO_PESSOAL NUMBER NOT NULL,
    NOME_LOGIN VARCHAR2(100) NOT NULL,
    SENHA_LOGIN VARCHAR2(100) NOT NULL, 
    CONSTRAINT CHPRIMA PRIMARY KEY (ID),
    CONSTRAINT C_FOREI FOREIGN KEY (DADO_PESSOAL) REFERENCES DADO_PESSOAL (ID)
);

CREATE TABLE GERENTE(
    ID INT,
    DADO_PESSOAL NUMBER,
    NOME_LOGIN VARCHAR2(100),
    SENHA_LOGIN VARCHAR2(100),
    CONSTRAINT CP PRIMARY KEY (ID ),
    CONSTRAINT CF FOREIGN KEY (DADO_PESSOAL) REFERENCES DADO_PESSOAL (ID)
);

CREATE TABLE TABELA_CLIENTE(
    ID NUMBER,
    DADO_PESSOAL NUMBER,
    CONSTRAINT C_P PRIMARY KEY (ID),
    CONSTRAINT C_F FOREIGN KEY (DADO_PESSOAL) REFERENCES DADO_PESSOAL (ID)
);

CREATE TABLE TABELA_PRODUTO (
    CODIGO NUMBER,
    VALOR DECIMAL(10,2),
    DESCRICAO VARCHAR2(200),
    ESTOQUE NUMBER,
    CODIGO_BARRAS VARCHAR2(150),
    NOME VARCHAR2(150),
    CONSTRAINT CH_FIR PRIMARY KEY (CODIGO)
);

CREATE TABLE TABELA_ATENDE (
    ID NUMBER,
    NOME_OPERADOR VARCHAR2(150),
    NOME_CLIENTE VARCHAR2(150),
    VALOR_FINAL DECIMAL(10,2),
    DATA_COMPRA VARCHAR2(30),
    CONSTRAINT CPR PRIMARY KEY (ID)
);

CREATE TABLE TABELA_COMPRA (
    NUMERO_ATENDE NUMBER,
    ID_PRODUTO NUMBER,
    CONSTRAINT C_FFF FOREIGN KEY (NUMERO_ATENDE ) REFERENCES TABELA_ATENDE(ID)
);