/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistematabica.view.principal;

import br.com.sistematabica.view.Style;

/**
 *
 * @author Joel
 */
public class EsqueceuSenhaGUI extends javax.swing.JFrame {

    Style style = new Style();
    
    /**
     * Creates new form EsqueceuSenhaGUI
     */
    public EsqueceuSenhaGUI() {
        initComponents();
        
        style.jLabelEditImage(lblLogo, "/br/com/sistematabica/imagens/sistema/icones/logo.png");
        style.jPanelEditColor(pnlLogin, 255, 255, 255);
        style.jLabelEditColor(lblVersionId, 255, 255, 255);
        style.default_JPanelBackground(pnlLogo);
        style.default_JLabelForeground(lblEmail);
        style.default_JLabelForeground(lblNovaSenha);
        style.default_JLabelForeground(lblVoltar);
        style.default_JLabelForeground(lblVoltar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        lblVersionId = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblExitErro = new javax.swing.JLabel();
        lblEsqueceuSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblNovaSenha = new javax.swing.JLabel();
        lblEnviar = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLogo.setBackground(new java.awt.Color(54, 52, 66));
        pnlLogo.setLayout(null);

        lblVersionId.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblVersionId.setForeground(new java.awt.Color(255, 255, 255));
        lblVersionId.setText("versão 1.0.0");
        pnlLogo.add(lblVersionId);
        lblVersionId.setBounds(130, 520, 130, 30);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/logo.png"))); // NOI18N
        pnlLogo.add(lblLogo);
        lblLogo.setBounds(120, 120, 150, 260);

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enviar");
        pnlLogin.add(jLabel1);
        jLabel1.setBounds(220, 330, 130, 40);

        lblExitErro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitErroMouseClicked(evt);
            }
        });
        pnlLogin.add(lblExitErro);
        lblExitErro.setBounds(356, 480, 50, 80);

        lblEsqueceuSenha.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblEsqueceuSenha.setForeground(new java.awt.Color(115, 115, 115));
        lblEsqueceuSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEsqueceuSenha.setText("Esqueceu senha");
        pnlLogin.add(lblEsqueceuSenha);
        lblEsqueceuSenha.setBounds(10, 50, 380, 70);
        pnlLogin.add(txtUsuario);
        txtUsuario.setBounds(40, 220, 310, 30);

        lblEmail.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(115, 115, 115));
        lblEmail.setText("e-mail:");
        pnlLogin.add(lblEmail);
        lblEmail.setBounds(40, 200, 60, 15);

        lblNovaSenha.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblNovaSenha.setForeground(new java.awt.Color(115, 115, 115));
        lblNovaSenha.setText("Nova senha:");
        pnlLogin.add(lblNovaSenha);
        lblNovaSenha.setBounds(40, 260, 80, 15);

        lblEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/backgroundVerdeClaro.png"))); // NOI18N
        lblEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnviarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnviarMouseExited(evt);
            }
        });
        pnlLogin.add(lblEnviar);
        lblEnviar.setBounds(220, 330, 130, 40);

        lblError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblErrorMouseClicked(evt);
            }
        });
        pnlLogin.add(lblError);
        lblError.setBounds(0, 480, 400, 80);
        pnlLogin.add(txtSenha);
        txtSenha.setBounds(40, 280, 310, 30);

        lblVoltar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblVoltar.setForeground(new java.awt.Color(115, 115, 115));
        lblVoltar.setText("voltar");
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });
        pnlLogin.add(lblVoltar);
        lblVoltar.setBounds(170, 330, 50, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitErroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitErroMouseClicked
        style.jLabelEditImage(lblError,"");
    }//GEN-LAST:event_lblExitErroMouseClicked

    private void lblEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarMouseClicked

    }//GEN-LAST:event_lblEnviarMouseClicked

    private void lblEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarMouseEntered
        style.jLabelEditImage(lblEnviar,"/br/com/sistematabica/imagens/sistema/icones/backgroundVerdeEscuro.png");
    }//GEN-LAST:event_lblEnviarMouseEntered

    private void lblEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarMouseExited
        style.jLabelEditImage(lblEnviar,"/br/com/sistematabica/imagens/sistema/icones/backgroundVerdeClaro.png");
    }//GEN-LAST:event_lblEnviarMouseExited

    private void lblErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblErrorMouseClicked

    }//GEN-LAST:event_lblErrorMouseClicked

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenhaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenhaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenhaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenhaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EsqueceuSenhaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnviar;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblEsqueceuSenha;
    private javax.swing.JLabel lblExitErro;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNovaSenha;
    private javax.swing.JLabel lblVersionId;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
