
package br.com.sistematabica.view.catalogo;

import br.com.sistematabica.controller.ProdutoController;
import br.com.sistematabica.model.Produto;
import br.com.sistematabica.model.tablemodel.ProdutoTableModel;
import br.com.sistematabica.view.Style;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**Tela do produto.
 * 
 * @author Joel Henrique
 * @author Evelyn Mayara
 * @author Lucas Gabriel
 * 
 * @version 1.00
 * 
 */
public class ProdutoGUI extends javax.swing.JFrame {

    private Style style = new Style();
    ProdutoController produtoController = new ProdutoController();
    ProdutoTableModel produtoTableModel = new ProdutoTableModel();
    
    /**
     * Creates new form TelaCatalogo
     */
    public ProdutoGUI() {
        initComponents();
    }

    /**Construtor que recebe todos os produtos para seta na view.
     * 
     * @author Joel Henrique
     * @author Evelyn Mayara
     * @author Lucas Gabriel
     * 
     * @param selecionarProduto
     * 
     */
    public ProdutoGUI(ArrayList<Produto> selecionarProduto) {
        
        this();
        
        for(Produto i : selecionarProduto)
            produtoTableModel.addRow(i);
        
        jTable1.setModel(produtoTableModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSair = new javax.swing.JLabel();
        lblRelacao = new javax.swing.JLabel();
        lblExcluir = new javax.swing.JLabel();
        lblAlterar = new javax.swing.JLabel();
        lblNovo = new javax.swing.JLabel();
        pnlNovo = new javax.swing.JPanel();
        lblTextNovo = new javax.swing.JLabel();
        lblIconNovo = new javax.swing.JLabel();
        pnlAlterar = new javax.swing.JPanel();
        lblTextAlterar = new javax.swing.JLabel();
        lblIconAlterar = new javax.swing.JLabel();
        pnlExcluir = new javax.swing.JPanel();
        lblTextExcluir = new javax.swing.JLabel();
        lblIconExcluir = new javax.swing.JLabel();
        pnlRelacao = new javax.swing.JPanel();
        lblTextRelacao = new javax.swing.JLabel();
        lblIconRelacao = new javax.swing.JLabel();
        pnlSair = new javax.swing.JPanel();
        lblTextSair = new javax.swing.JLabel();
        lblIconSair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produto");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(18, 29, 49));
        jPanel2.setLayout(null);

        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });
        jPanel2.add(lblSair);
        lblSair.setBounds(910, 0, 75, 100);

        lblRelacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRelacaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRelacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRelacaoMouseExited(evt);
            }
        });
        jPanel2.add(lblRelacao);
        lblRelacao.setBounds(830, 0, 75, 100);

        lblExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExcluirMouseExited(evt);
            }
        });
        jPanel2.add(lblExcluir);
        lblExcluir.setBounds(760, 0, 75, 100);

        lblAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlterarMouseExited(evt);
            }
        });
        jPanel2.add(lblAlterar);
        lblAlterar.setBounds(680, 0, 75, 100);

        lblNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNovoMouseExited(evt);
            }
        });
        jPanel2.add(lblNovo);
        lblNovo.setBounds(610, 0, 75, 100);

        pnlNovo.setBackground(new java.awt.Color(18, 29, 49));
        pnlNovo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextNovo.setForeground(new java.awt.Color(255, 255, 255));
        lblTextNovo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextNovo.setText("Novo");
        pnlNovo.add(lblTextNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconNovo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/add.png"))); // NOI18N
        pnlNovo.add(lblIconNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlNovo);
        pnlNovo.setBounds(610, 0, 75, 100);

        pnlAlterar.setBackground(new java.awt.Color(18, 29, 49));
        pnlAlterar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextAlterar.setForeground(new java.awt.Color(255, 255, 255));
        lblTextAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextAlterar.setText("Alterar");
        pnlAlterar.add(lblTextAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/edit.png"))); // NOI18N
        pnlAlterar.add(lblIconAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlAlterar);
        pnlAlterar.setBounds(680, 0, 75, 100);

        pnlExcluir.setBackground(new java.awt.Color(18, 29, 49));
        pnlExcluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextExcluir.setForeground(new java.awt.Color(255, 255, 255));
        lblTextExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextExcluir.setText("Excluir");
        pnlExcluir.add(lblTextExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/delete.png"))); // NOI18N
        pnlExcluir.add(lblIconExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlExcluir);
        pnlExcluir.setBounds(760, 0, 75, 100);

        pnlRelacao.setBackground(new java.awt.Color(18, 29, 49));
        pnlRelacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextRelacao.setForeground(new java.awt.Color(255, 255, 255));
        lblTextRelacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextRelacao.setText("Relação");
        pnlRelacao.add(lblTextRelacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconRelacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconRelacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/relacao.png"))); // NOI18N
        pnlRelacao.add(lblIconRelacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlRelacao);
        pnlRelacao.setBounds(830, 0, 75, 100);

        pnlSair.setBackground(new java.awt.Color(18, 29, 49));
        pnlSair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextSair.setForeground(new java.awt.Color(255, 255, 255));
        lblTextSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextSair.setText("Sair");
        pnlSair.add(lblTextSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/exit.png"))); // NOI18N
        pnlSair.add(lblIconSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlSair);
        pnlSair.setBounds(910, 0, 75, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/logoEsq.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 300, 80);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Elmano > Marcelo > Eduardo", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(18, 29, 49));
        jTable1.setSelectionBackground(new java.awt.Color(18, 29, 49));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 980, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblRelacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacaoMouseClicked
        produtoController.relacao();
    }//GEN-LAST:event_lblRelacaoMouseClicked

    private void lblExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseClicked

        // ser algum dado estiver selecionado na tabela
        if(jTable1.getSelectedRow() != -1) {
           
            // se a remoção do banco de dados foi feita com sucesso
            if(produtoController.excluir(produtoTableModel.getList(jTable1.getSelectedRow()).getCodigo())) {
                
   
                // remover da tabela
                produtoTableModel.removeRow(jTable1.getSelectedRow());
                
            }else {
                JOptionPane.showMessageDialog(null,"não foi possivel remover do banco de dados");
            }
            
            
        }else if(jTable1.getSelectedRow() == -1){
           // JOptionPane.showMessageDialog(null,"Operador não selecionado");
        }
    }//GEN-LAST:event_lblExcluirMouseClicked

    private void lblAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseClicked
        // se algum dado estiver selecionado na tabela
        if (jTable1.getSelectedRow() != -1) {
            
            System.out.println("CODIGO +" + produtoTableModel.getList(jTable1.getSelectedRow()).getCodigo());
            
            this.dispose();
            produtoController.alterarGUI(produtoTableModel.getList(jTable1.getSelectedRow()));

        } else if (jTable1.getSelectedRow() == -1) {
             JOptionPane.showMessageDialog(null,"Operador não selecionado");
        }
    }//GEN-LAST:event_lblAlterarMouseClicked

    private void lblNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoMouseClicked
        this.dispose();      
        produtoController.novoGUI();
    }//GEN-LAST:event_lblNovoMouseClicked

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        style.jPanelEditColor(pnlSair, 8, 18, 38);
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        style.jPanelEditColor(pnlSair, 18, 29, 49);
    }//GEN-LAST:event_lblSairMouseExited

    private void lblRelacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacaoMouseEntered
        style.jPanelEditColor(pnlRelacao, 8, 18, 38);
    }//GEN-LAST:event_lblRelacaoMouseEntered

    private void lblRelacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacaoMouseExited
        style.jPanelEditColor(pnlRelacao, 18, 29, 49);
    }//GEN-LAST:event_lblRelacaoMouseExited

    private void lblExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseEntered
        style.jPanelEditColor(pnlExcluir, 8, 18, 38);
    }//GEN-LAST:event_lblExcluirMouseEntered

    private void lblExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseExited
        style.jPanelEditColor(pnlExcluir, 18, 29, 49);
    }//GEN-LAST:event_lblExcluirMouseExited

    private void lblAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseEntered
        style.jPanelEditColor(pnlAlterar, 8, 18, 38);
    }//GEN-LAST:event_lblAlterarMouseEntered

    private void lblAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseExited
        style.jPanelEditColor(pnlAlterar, 18, 29, 49);
    }//GEN-LAST:event_lblAlterarMouseExited

    private void lblNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoMouseEntered
        style.jPanelEditColor(pnlNovo, 8, 18, 38);
    }//GEN-LAST:event_lblNovoMouseEntered

    private void lblNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoMouseExited
        style.jPanelEditColor(pnlNovo, 18, 29, 49);
    }//GEN-LAST:event_lblNovoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAlterar;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblIconAlterar;
    private javax.swing.JLabel lblIconExcluir;
    private javax.swing.JLabel lblIconNovo;
    private javax.swing.JLabel lblIconRelacao;
    private javax.swing.JLabel lblIconSair;
    private javax.swing.JLabel lblNovo;
    private javax.swing.JLabel lblRelacao;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblTextAlterar;
    private javax.swing.JLabel lblTextExcluir;
    private javax.swing.JLabel lblTextNovo;
    private javax.swing.JLabel lblTextRelacao;
    private javax.swing.JLabel lblTextSair;
    private javax.swing.JPanel pnlAlterar;
    private javax.swing.JPanel pnlExcluir;
    private javax.swing.JPanel pnlNovo;
    private javax.swing.JPanel pnlRelacao;
    private javax.swing.JPanel pnlSair;
    // End of variables declaration//GEN-END:variables
}
