
package br.com.sistematabica.view.configuracoes;

import br.com.sistematabica.view.Style;
import javax.swing.JOptionPane;

/**Tela de atualizações.
 * 
 * @author Joel Henrique
 * @author Evelyn Mayara
 * @author Lucas Gabriel
 * 
 * @version 1.00
 * 
 */
public class AtualizacoesGUI extends javax.swing.JFrame {

    Style style = new Style();
    
    public AtualizacoesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblButtonTitulo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblButtonBackground = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblButtonTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblButtonTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblButtonTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblButtonTitulo.setText("Atualizar");
        lblButtonTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblButtonTituloMouseClicked(evt);
            }
        });
        jPanel1.add(lblButtonTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 130, 40));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Atualizações de software");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 270, 50));

        lblButtonBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/backgroundVermelhoClaro.png"))); // NOI18N
        lblButtonBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblButtonBackgroundMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblButtonBackgroundMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblButtonBackgroundMouseExited(evt);
            }
        });
        jPanel1.add(lblButtonBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 130, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/backgroundStarBlack.png"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblButtonBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonBackgroundMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblButtonBackgroundMouseClicked

    private void lblButtonBackgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonBackgroundMouseEntered
        style.jLabelEditImage(lblButtonBackground, "/br/com/sistematabica/imagens/sistema/icones/backgroundVermelhoEscuro.png");
    }//GEN-LAST:event_lblButtonBackgroundMouseEntered

    private void lblButtonBackgroundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonBackgroundMouseExited
        style.jLabelEditImage(lblButtonBackground, "/br/com/sistematabica/imagens/sistema/icones/backgroundVermelhoClaro.png");
    }//GEN-LAST:event_lblButtonBackgroundMouseExited

    private void lblButtonTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonTituloMouseClicked
        JOptionPane.showMessageDialog(null, "Ops, função não disponivel nessa versão");
    }//GEN-LAST:event_lblButtonTituloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizacoesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizacoesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizacoesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizacoesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizacoesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblButtonBackground;
    private javax.swing.JLabel lblButtonTitulo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
