
package br.com.sistematabica.view;

import br.com.sistematabica.model.DadoPessoal;
import br.com.sistematabica.view.cadastrar.conta.cliente.CadastrarClienteGUI;
import br.com.sistematabica.view.cadastrar.conta.OperadorCaixa.CadastrarOperadorCaixaGUI;
import br.com.sistematabica.view.cadastrar.conta.gerente.CadastrarGerenteGUI;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Joel
 */
public class CadastrarPerfilIconGUI extends javax.swing.JFrame {
    
    private Object objDadoConta;
    private static String url = "perfil";
    private Style style = new Style();
    /**
     * Creates new form PerfilIconGUI
     */
    public CadastrarPerfilIconGUI() {
        initComponents();
    }
    
    /**Construtor que vai receber uma conta.
     * 
     * @author Joel Henrique
     * @author Evelyn Mayara
     * @author Lucas Gabriel
     * 
     * @param conta
     * 
     */
    public CadastrarPerfilIconGUI(Object conta) {
        this();
        this.objDadoConta = conta;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        select1 = new javax.swing.JLabel();
        select2 = new javax.swing.JLabel();
        select3 = new javax.swing.JLabel();
        select4 = new javax.swing.JLabel();
        select5 = new javax.swing.JLabel();
        select6 = new javax.swing.JLabel();
        select7 = new javax.swing.JLabel();
        select8 = new javax.swing.JLabel();
        select9 = new javax.swing.JLabel();
        select10 = new javax.swing.JLabel();
        select11 = new javax.swing.JLabel();
        select12 = new javax.swing.JLabel();
        select13 = new javax.swing.JLabel();
        select14 = new javax.swing.JLabel();
        select15 = new javax.swing.JLabel();
        select16 = new javax.swing.JLabel();
        select17 = new javax.swing.JLabel();
        select18 = new javax.swing.JLabel();
        select19 = new javax.swing.JLabel();
        select20 = new javax.swing.JLabel();
        select21 = new javax.swing.JLabel();
        select22 = new javax.swing.JLabel();
        select23 = new javax.swing.JLabel();
        select24 = new javax.swing.JLabel();
        select25 = new javax.swing.JLabel();
        select26 = new javax.swing.JLabel();
        select27 = new javax.swing.JLabel();
        select28 = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        lblG = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        lblJ = new javax.swing.JLabel();
        lblK = new javax.swing.JLabel();
        lblL = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        lblS = new javax.swing.JLabel();
        lblO = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        lblU = new javax.swing.JLabel();
        lblQ = new javax.swing.JLabel();
        lblR = new javax.swing.JLabel();
        lblW = new javax.swing.JLabel();
        lblElias = new javax.swing.JLabel();
        lblV = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar imagem");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(select1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 62, 62));
        jPanel1.add(select2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 62, 62));
        jPanel1.add(select3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 62, 62));
        jPanel1.add(select4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 62, 62));
        jPanel1.add(select5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 62, 62));
        jPanel1.add(select6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 62, 62));
        jPanel1.add(select7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 62, 62));
        jPanel1.add(select8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 62, 62));
        jPanel1.add(select9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 62, 62));
        jPanel1.add(select10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 62, 62));
        jPanel1.add(select11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 62, 62));
        jPanel1.add(select12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 62, 62));
        jPanel1.add(select13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 62, 62));
        jPanel1.add(select14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 62, 62));
        jPanel1.add(select15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 62, 62));
        jPanel1.add(select16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 62, 62));
        jPanel1.add(select17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 62, 62));
        jPanel1.add(select18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 62, 62));
        jPanel1.add(select19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 62, 62));
        jPanel1.add(select20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 62, 62));
        jPanel1.add(select21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 62, 62));
        jPanel1.add(select22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 62, 62));
        jPanel1.add(select23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 62, 62));
        jPanel1.add(select24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 62, 62));
        jPanel1.add(select25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 62, 62));
        jPanel1.add(select26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 62, 62));
        jPanel1.add(select27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 62, 62));

        select28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/selecionado.png"))); // NOI18N
        jPanel1.add(select28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 62, 62));

        lblF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/fp.png"))); // NOI18N
        lblF.setText("jLabel1");
        lblF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFMouseClicked(evt);
            }
        });
        jPanel1.add(lblF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 62, -1));

        lblB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/bp.png"))); // NOI18N
        lblB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBMouseClicked(evt);
            }
        });
        jPanel1.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 62, -1));

        lblC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/cp.png"))); // NOI18N
        lblC.setText("jLabel1");
        lblC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCMouseClicked(evt);
            }
        });
        jPanel1.add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 62, -1));

        lblD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/dp.png"))); // NOI18N
        lblD.setText("jLabel1");
        lblD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDMouseClicked(evt);
            }
        });
        jPanel1.add(lblD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 62, -1));

        lblE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/ep.png"))); // NOI18N
        lblE.setText("jLabel1");
        lblE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEMouseClicked(evt);
            }
        });
        jPanel1.add(lblE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 62, -1));

        lblG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/gp.png"))); // NOI18N
        lblG.setText("jLabel1");
        lblG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGMouseClicked(evt);
            }
        });
        jPanel1.add(lblG, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 62, -1));

        lblH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/hp.png"))); // NOI18N
        lblH.setText("jLabel1");
        lblH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHMouseClicked(evt);
            }
        });
        jPanel1.add(lblH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 62, -1));

        lblM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/mp.png"))); // NOI18N
        lblM.setText("jLabel1");
        lblM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMMouseClicked(evt);
            }
        });
        jPanel1.add(lblM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 62, -1));

        lblI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/ip.png"))); // NOI18N
        lblI.setText("jLabel1");
        lblI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIMouseClicked(evt);
            }
        });
        jPanel1.add(lblI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 62, -1));

        lblJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/jp.png"))); // NOI18N
        lblJ.setText("jLabel1");
        lblJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJMouseClicked(evt);
            }
        });
        jPanel1.add(lblJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 62, -1));

        lblK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/kp.png"))); // NOI18N
        lblK.setText("jLabel1");
        lblK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKMouseClicked(evt);
            }
        });
        jPanel1.add(lblK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 62, -1));

        lblL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/lp.png"))); // NOI18N
        lblL.setText("jLabel1");
        lblL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLMouseClicked(evt);
            }
        });
        jPanel1.add(lblL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 62, -1));

        lblN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/np.png"))); // NOI18N
        lblN.setText("jLabel1");
        lblN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNMouseClicked(evt);
            }
        });
        jPanel1.add(lblN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 62, -1));

        lblP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/pq.png"))); // NOI18N
        lblP.setText("jLabel1");
        lblP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPMouseClicked(evt);
            }
        });
        jPanel1.add(lblP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 62, -1));

        lblS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/sp.png"))); // NOI18N
        lblS.setText("jLabel1");
        lblS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSMouseClicked(evt);
            }
        });
        jPanel1.add(lblS, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 62, -1));

        lblO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/op.png"))); // NOI18N
        lblO.setText("jLabel1");
        lblO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOMouseClicked(evt);
            }
        });
        jPanel1.add(lblO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 62, -1));

        lblT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/tp.png"))); // NOI18N
        lblT.setText("jLabel1");
        lblT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTMouseClicked(evt);
            }
        });
        jPanel1.add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 62, -1));

        lblU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/up.png"))); // NOI18N
        lblU.setText("jLabel1");
        lblU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUMouseClicked(evt);
            }
        });
        jPanel1.add(lblU, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 62, -1));

        lblQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/qp.png"))); // NOI18N
        lblQ.setText("jLabel1");
        lblQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQMouseClicked(evt);
            }
        });
        jPanel1.add(lblQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 62, -1));

        lblR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/rp.png"))); // NOI18N
        lblR.setText("jLabel1");
        lblR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRMouseClicked(evt);
            }
        });
        jPanel1.add(lblR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 62, -1));

        lblW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/wp.png"))); // NOI18N
        lblW.setText("jLabel1");
        lblW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWMouseClicked(evt);
            }
        });
        jPanel1.add(lblW, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 62, -1));

        lblElias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/eliasp.png"))); // NOI18N
        lblElias.setText("jLabel1");
        lblElias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliasMouseClicked(evt);
            }
        });
        jPanel1.add(lblElias, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 62, -1));

        lblV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/vp.png"))); // NOI18N
        lblV.setText("jLabel1");
        lblV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVMouseClicked(evt);
            }
        });
        jPanel1.add(lblV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 62, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/logop.png"))); // NOI18N
        lblLogo.setText("jLabel1");
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 62, -1));

        lblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/perfilp.png"))); // NOI18N
        lblPerfil.setText("jLabel1");
        lblPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerfilMouseClicked(evt);
            }
        });
        jPanel1.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 62, -1));

        lblX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/xp.png"))); // NOI18N
        lblX.setText("jLabel1");
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });
        jPanel1.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 62, -1));

        lblY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/yp.png"))); // NOI18N
        lblY.setText("jLabel1");
        lblY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYMouseClicked(evt);
            }
        });
        jPanel1.add(lblY, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 62, -1));

        lblA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/usuario/contas/ap.png"))); // NOI18N
        lblA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAMouseClicked(evt);
            }
        });
        jPanel1.add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 62, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecionar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/backgroundVerdeClaro.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 130, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /** Método que vai tirar todas as marcações(png) de cada foto da view
     * 
     * @author Joel Henrique Silva Santos
     * @author Evelyn Mayara da Silva Santos
     * @author Lucas Gabriel Silva Santos
     * 
     */
    public void tirarMarcadorTudo() {
    
        ArrayList<JLabel> labels = new ArrayList<>();
        
        labels.add(select1);
        labels.add(select1);
        labels.add(select2);
        labels.add(select3);
        labels.add(select4);
        labels.add(select5);
        labels.add(select6);
        labels.add(select7);
        labels.add(select8);
        labels.add(select9);
        labels.add(select10);
        labels.add(select11);
        labels.add(select12);
        labels.add(select13);
        labels.add(select14);
        labels.add(select15);
        labels.add(select16);
        labels.add(select17);
        labels.add(select18);
        labels.add(select19);
        labels.add(select20);
        labels.add(select21);
        labels.add(select22);
        labels.add(select23);
        labels.add(select24);
        labels.add(select25);
        labels.add(select26);
        labels.add(select27);
        labels.add(select28);
        
        for(JLabel i : labels) {
            style.jLabelEditImage(i, "");
        }
    }
    
    private void lblAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select1, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "a";
    }//GEN-LAST:event_lblAMouseClicked

    private void lblBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select2, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "b";
    }//GEN-LAST:event_lblBMouseClicked

    private void lblCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select3, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "c";
    }//GEN-LAST:event_lblCMouseClicked

    private void lblDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select4, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "d";
    }//GEN-LAST:event_lblDMouseClicked

    private void lblEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select5, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "e";
    }//GEN-LAST:event_lblEMouseClicked

    private void lblFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select6, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "f";
    }//GEN-LAST:event_lblFMouseClicked

    private void lblGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select7, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "g";
    }//GEN-LAST:event_lblGMouseClicked

    private void lblHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select8, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "h";
    }//GEN-LAST:event_lblHMouseClicked

    private void lblIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select9, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "i";
    }//GEN-LAST:event_lblIMouseClicked

    private void lblJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select10, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "j";
    }//GEN-LAST:event_lblJMouseClicked

    private void lblKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select11, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "k";
    }//GEN-LAST:event_lblKMouseClicked

    private void lblLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select12, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "l";
    }//GEN-LAST:event_lblLMouseClicked

    private void lblMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select13, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "m";
    }//GEN-LAST:event_lblMMouseClicked

    private void lblNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select14, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "n";
    }//GEN-LAST:event_lblNMouseClicked

    private void lblOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select15, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "o";
    }//GEN-LAST:event_lblOMouseClicked

    private void lblPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select16, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "p";
    }//GEN-LAST:event_lblPMouseClicked

    private void lblQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select17, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "q";
    }//GEN-LAST:event_lblQMouseClicked

    private void lblRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select18, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "r";
    }//GEN-LAST:event_lblRMouseClicked

    private void lblSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select19, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "s";
    }//GEN-LAST:event_lblSMouseClicked

    private void lblTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select20, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "t";
    }//GEN-LAST:event_lblTMouseClicked

    private void lblUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select21, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "u";
    }//GEN-LAST:event_lblUMouseClicked

    private void lblVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select22, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "v";
    }//GEN-LAST:event_lblVMouseClicked

    private void lblWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select23, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "w";
    }//GEN-LAST:event_lblWMouseClicked

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select24, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "x";
    }//GEN-LAST:event_lblXMouseClicked

    private void lblYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select25, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "y";
    }//GEN-LAST:event_lblYMouseClicked

    private void lblEliasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliasMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select26, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "elias";
    }//GEN-LAST:event_lblEliasMouseClicked

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select27, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "logo";
    }//GEN-LAST:event_lblLogoMouseClicked

    private void lblPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilMouseClicked
        tirarMarcadorTudo();
        style.jLabelEditImage(select28, "/br/com/sistematabica/imagens/sistema/icones/selecionado.png");
        url = "perfil";
    }//GEN-LAST:event_lblPerfilMouseClicked

   /** Evento que quando clica vai abrir uma tela de cadastro ao de alteração de uma conta ou produto
     * 
     * @author Joel Henrique Silva Santos
     * @author Evelyn Mayara da Silva Santos
     * @author Lucas Gabriel Silva Santos
     * 
     */
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        if(objDadoConta instanceof DadoPessoal) {
            
            if(((DadoPessoal)objDadoConta).getTipo().equalsIgnoreCase("cliente")) {
            
                DadoPessoal dadoPessoalCliente = (DadoPessoal) objDadoConta;
                dadoPessoalCliente.setURLFoto(url);
                
                CadastrarClienteGUI cadastrarClienteGUI = new CadastrarClienteGUI(dadoPessoalCliente);
                cadastrarClienteGUI.setVisible(true);
                
                System.out.println("SHOW: CadastrarClienteGUI");
                
                this.dispose();
                
            }else if(((DadoPessoal)objDadoConta).getTipo().equalsIgnoreCase("gerente")) {
            
                DadoPessoal novoDadoPessoal = (DadoPessoal) objDadoConta;
                novoDadoPessoal.setURLFoto(url);
                
                CadastrarGerenteGUI cadastrarGerenteGUI = new CadastrarGerenteGUI(novoDadoPessoal);
                cadastrarGerenteGUI.setVisible(true);
                
                this.dispose();
                
            }else if(((DadoPessoal)objDadoConta).getTipo().equalsIgnoreCase("operadorCaixa")) {
            
                DadoPessoal dadoPessoalOperadorCaixa = (DadoPessoal) objDadoConta;
                dadoPessoalOperadorCaixa.setURLFoto(url);
                
                CadastrarOperadorCaixaGUI cadastrarOperadorCaixaGUI = new CadastrarOperadorCaixaGUI(dadoPessoalOperadorCaixa);
                cadastrarOperadorCaixaGUI.setVisible(true);

                System.out.println("SHOW: CadastrarOperadorCaixaGUI");
                
                this.dispose();
                
            }
            
        }
        

           
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPerfilIconGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPerfilIconGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPerfilIconGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPerfilIconGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPerfilIconGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblElias;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblJ;
    private javax.swing.JLabel lblK;
    private javax.swing.JLabel lblL;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblO;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblQ;
    private javax.swing.JLabel lblR;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblU;
    private javax.swing.JLabel lblV;
    private javax.swing.JLabel lblW;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JLabel select1;
    private javax.swing.JLabel select10;
    private javax.swing.JLabel select11;
    private javax.swing.JLabel select12;
    private javax.swing.JLabel select13;
    private javax.swing.JLabel select14;
    private javax.swing.JLabel select15;
    private javax.swing.JLabel select16;
    private javax.swing.JLabel select17;
    private javax.swing.JLabel select18;
    private javax.swing.JLabel select19;
    private javax.swing.JLabel select2;
    private javax.swing.JLabel select20;
    private javax.swing.JLabel select21;
    private javax.swing.JLabel select22;
    private javax.swing.JLabel select23;
    private javax.swing.JLabel select24;
    private javax.swing.JLabel select25;
    private javax.swing.JLabel select26;
    private javax.swing.JLabel select27;
    private javax.swing.JLabel select28;
    private javax.swing.JLabel select3;
    private javax.swing.JLabel select4;
    private javax.swing.JLabel select5;
    private javax.swing.JLabel select6;
    private javax.swing.JLabel select7;
    private javax.swing.JLabel select8;
    private javax.swing.JLabel select9;
    // End of variables declaration//GEN-END:variables
}
