
package br.com.sistematabica.view.contas;

import br.com.sistematabica.controller.GerenteController;
import br.com.sistematabica.model.Gerente;
import br.com.sistematabica.view.Style;

/**Tela do gerente.
 * 
 * @author Joel Henrique
 * @author Evelyn Mayara
 * @author Lucas Gabriel
 * 
 * @version 1.00
 * 
 */
public class GerenteGUI extends javax.swing.JFrame {

    GerenteController gerenteController = new GerenteController();
    Gerente gerenteAtual;
    Style style = new Style();
    /**
     * Creates new form GerenteGUI
     */
    public GerenteGUI() {
        initComponents();
    }

    /**Classe Controller que vai controlar tudo relacionado a cliente.
     * 
     * @author Joel Henrique
     * @author Evelyn Mayara
     * @author Lucas Gabriel
     * 
     * @param gerente Gerente - um objeto gerente
     * 
     */
    public GerenteGUI(Gerente gerente) {
        this();
        this.gerenteAtual = gerente;
        lblTitulo.setText("Gerente logado: "+gerente.getDados().getNomeCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblButtonDeletar = new javax.swing.JLabel();
        lblButtonBackgroundDeletar = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerente");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(18, 29, 49));
        jPanel2.setLayout(null);

        lblButtonDeletar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblButtonDeletar.setForeground(new java.awt.Color(255, 255, 255));
        lblButtonDeletar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblButtonDeletar.setText("Deletar gerente");
        lblButtonDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblButtonDeletarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblButtonDeletarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblButtonDeletarMouseExited(evt);
            }
        });
        jPanel2.add(lblButtonDeletar);
        lblButtonDeletar.setBounds(160, 130, 150, 40);

        lblButtonBackgroundDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/backgroundVermelhoClaro.png"))); // NOI18N
        lblButtonBackgroundDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblButtonBackgroundDeletarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblButtonBackgroundDeletarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblButtonBackgroundDeletarMouseExited(evt);
            }
        });
        jPanel2.add(lblButtonBackgroundDeletar);
        lblButtonBackgroundDeletar.setBounds(160, 130, 150, 40);

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gerente logado: Patolino");
        jPanel2.add(lblTitulo);
        lblTitulo.setBounds(30, 20, 410, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblButtonDeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonDeletarMouseClicked
        System.out.println("NUMERO REGISTRO: " + gerenteAtual.getDados().getNumeroRegistro());
        new GerenteController().deletarGerente(gerenteAtual.getDados().getNumeroRegistro());
        this.dispose();
    }//GEN-LAST:event_lblButtonDeletarMouseClicked

    private void lblButtonBackgroundDeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonBackgroundDeletarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblButtonBackgroundDeletarMouseClicked

    private void lblButtonBackgroundDeletarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonBackgroundDeletarMouseEntered
        style.jLabelEditImage(lblButtonBackgroundDeletar, "/br/com/sistematabica/imagens/sistema/icones/backgroundVerdeEscuro.png");
    }//GEN-LAST:event_lblButtonBackgroundDeletarMouseEntered

    private void lblButtonBackgroundDeletarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonBackgroundDeletarMouseExited
        style.jLabelEditImage(lblButtonBackgroundDeletar, "/br/com/sistematabica/imagens/sistema/icones/backgroundVerdeClaro.png");
    }//GEN-LAST:event_lblButtonBackgroundDeletarMouseExited

    private void lblButtonDeletarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonDeletarMouseEntered
        style.jLabelEditImage(lblButtonBackgroundDeletar, "/br/com/sistematabica/imagens/sistema/icones/backgroundVermelhoEscuro.png");
    }//GEN-LAST:event_lblButtonDeletarMouseEntered

    private void lblButtonDeletarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButtonDeletarMouseExited
        style.jLabelEditImage(lblButtonBackgroundDeletar, "/br/com/sistematabica/imagens/sistema/icones/backgroundVermelhoClaro.png");
    }//GEN-LAST:event_lblButtonDeletarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblButtonBackgroundDeletar;
    private javax.swing.JLabel lblButtonDeletar;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
