
package br.com.sistematabica.view.contas;

import br.com.sistematabica.controller.OperadorCaixaController;
import br.com.sistematabica.model.Cliente;
import br.com.sistematabica.model.OperadorCaixa;
import br.com.sistematabica.model.tablemodel.OperadorCaixaTableModel;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**Tela do operador de caixa.
 * 
 * @author Joel Henrique
 * @author Evelyn Mayara
 * @author Lucas Gabriel
 * 
 * @version 1.00
 * 
 */
public class OperadorCaixaGUI extends javax.swing.JFrame {
    
    OperadorCaixaController operadorCaixaController = new OperadorCaixaController();
    OperadorCaixaTableModel operadorCaixaTableModel = new OperadorCaixaTableModel();
    Cliente cliente;
    /**
     * Creates new form TelaCadastroCliente
     */
    public OperadorCaixaGUI() {
        initComponents();

    }

    /**Construtor que seta na view todos os operadores.
     * 
     * @author Joel Henrique
     * @author Evelyn Mayara
     * @author Lucas Gabriel
     * 
     * @param todosOperadores ArrayList - todos os operadores
     * 
     */
    public OperadorCaixaGUI(ArrayList<OperadorCaixa> todosOperadores) {
        
        this();
        
        for(OperadorCaixa i : todosOperadores)
            operadorCaixaTableModel.addRow(i);
        
        jTable1.setModel(operadorCaixaTableModel);

    }

    public void mouseEntered(JPanel pnl1) {
        pnl1.setBackground(new Color(8, 18, 38));
    }
    
    public void mouseExited(JPanel pnl1) {
        pnl1.setBackground(new Color(18, 29, 49));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSair = new javax.swing.JLabel();
        lblRelacao = new javax.swing.JLabel();
        lblExcluir = new javax.swing.JLabel();
        lblAlterar = new javax.swing.JLabel();
        lblNovo = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        pnlImagem = new javax.swing.JPanel();
        lblTextImagem = new javax.swing.JLabel();
        lblIconImagem = new javax.swing.JLabel();
        pnlNovo = new javax.swing.JPanel();
        lblTextNovo = new javax.swing.JLabel();
        lblIconNovo = new javax.swing.JLabel();
        pnlAlterar = new javax.swing.JPanel();
        lblTextAlterar = new javax.swing.JLabel();
        lblIconAlterar = new javax.swing.JLabel();
        pnlExcluir = new javax.swing.JPanel();
        lblTextExcluir = new javax.swing.JLabel();
        lblIconExcluir = new javax.swing.JLabel();
        pnlRelacao = new javax.swing.JPanel();
        lblTextRelacao = new javax.swing.JLabel();
        lblIconRelacao = new javax.swing.JLabel();
        pnlSair = new javax.swing.JPanel();
        lblTextSair = new javax.swing.JLabel();
        lblIconSair = new javax.swing.JLabel();
        lblAlterar1 = new javax.swing.JLabel();
        lblExcluir1 = new javax.swing.JLabel();
        lblNovo1 = new javax.swing.JLabel();
        lblRelacao1 = new javax.swing.JLabel();
        pnlNovo1 = new javax.swing.JPanel();
        lblTextNovo1 = new javax.swing.JLabel();
        lblIconNovo1 = new javax.swing.JLabel();
        pnlAlterar1 = new javax.swing.JPanel();
        lblTextAlterar1 = new javax.swing.JLabel();
        lblIconAlterar1 = new javax.swing.JLabel();
        pnlExcluir1 = new javax.swing.JPanel();
        lblTextExcluir1 = new javax.swing.JLabel();
        lblIconExcluir1 = new javax.swing.JLabel();
        pnlRelacao1 = new javax.swing.JPanel();
        lblTextRelacao1 = new javax.swing.JLabel();
        lblIconRelacao1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operador");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(18, 29, 49));
        jPanel2.setLayout(null);

        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });
        jPanel2.add(lblSair);
        lblSair.setBounds(900, 0, 75, 100);

        lblRelacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRelacaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRelacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRelacaoMouseExited(evt);
            }
        });
        jPanel2.add(lblRelacao);
        lblRelacao.setBounds(830, 0, 75, 100);

        lblExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExcluirMouseExited(evt);
            }
        });
        jPanel2.add(lblExcluir);
        lblExcluir.setBounds(750, 0, 75, 100);

        lblAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlterarMouseExited(evt);
            }
        });
        jPanel2.add(lblAlterar);
        lblAlterar.setBounds(680, 0, 75, 100);

        lblNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNovoMouseExited(evt);
            }
        });
        jPanel2.add(lblNovo);
        lblNovo.setBounds(600, 0, 75, 100);

        lblImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImagemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagemMouseExited(evt);
            }
        });
        jPanel2.add(lblImagem);
        lblImagem.setBounds(522, 0, 75, 100);

        pnlImagem.setBackground(new java.awt.Color(18, 29, 49));
        pnlImagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextImagem.setForeground(new java.awt.Color(255, 255, 255));
        lblTextImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextImagem.setText("Imagem");
        pnlImagem.add(lblTextImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/image.png"))); // NOI18N
        pnlImagem.add(lblIconImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlImagem);
        pnlImagem.setBounds(522, 0, 75, 100);

        pnlNovo.setBackground(new java.awt.Color(18, 29, 49));
        pnlNovo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextNovo.setForeground(new java.awt.Color(255, 255, 255));
        lblTextNovo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextNovo.setText("Novo");
        pnlNovo.add(lblTextNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconNovo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/add.png"))); // NOI18N
        pnlNovo.add(lblIconNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlNovo);
        pnlNovo.setBounds(600, 0, 75, 100);

        pnlAlterar.setBackground(new java.awt.Color(18, 29, 49));
        pnlAlterar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextAlterar.setForeground(new java.awt.Color(255, 255, 255));
        lblTextAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextAlterar.setText("Alterar");
        pnlAlterar.add(lblTextAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/edit.png"))); // NOI18N
        pnlAlterar.add(lblIconAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlAlterar);
        pnlAlterar.setBounds(680, 0, 75, 100);

        pnlExcluir.setBackground(new java.awt.Color(18, 29, 49));
        pnlExcluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextExcluir.setForeground(new java.awt.Color(255, 255, 255));
        lblTextExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextExcluir.setText("Excluir");
        pnlExcluir.add(lblTextExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/delete.png"))); // NOI18N
        pnlExcluir.add(lblIconExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlExcluir);
        pnlExcluir.setBounds(750, 0, 75, 100);

        pnlRelacao.setBackground(new java.awt.Color(18, 29, 49));
        pnlRelacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextRelacao.setForeground(new java.awt.Color(255, 255, 255));
        lblTextRelacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextRelacao.setText("Relação");
        pnlRelacao.add(lblTextRelacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconRelacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconRelacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/relacao.png"))); // NOI18N
        pnlRelacao.add(lblIconRelacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlRelacao);
        pnlRelacao.setBounds(830, 0, 75, 100);

        pnlSair.setBackground(new java.awt.Color(18, 29, 49));
        pnlSair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextSair.setForeground(new java.awt.Color(255, 255, 255));
        lblTextSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextSair.setText("Sair");
        pnlSair.add(lblTextSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/exit.png"))); // NOI18N
        pnlSair.add(lblIconSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlSair);
        pnlSair.setBounds(900, 0, 75, 100);

        lblAlterar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlterar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlterar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlterar1MouseExited(evt);
            }
        });
        jPanel2.add(lblAlterar1);
        lblAlterar1.setBounds(748, 0, 75, 100);

        lblExcluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExcluir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExcluir1MouseExited(evt);
            }
        });
        jPanel2.add(lblExcluir1);
        lblExcluir1.setBounds(823, 0, 75, 100);

        lblNovo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNovo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNovo1MouseExited(evt);
            }
        });
        jPanel2.add(lblNovo1);
        lblNovo1.setBounds(673, 0, 75, 100);

        lblRelacao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRelacao1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRelacao1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRelacao1MouseExited(evt);
            }
        });
        jPanel2.add(lblRelacao1);
        lblRelacao1.setBounds(898, 0, 75, 100);

        pnlNovo1.setBackground(new java.awt.Color(18, 29, 49));
        pnlNovo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextNovo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextNovo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextNovo1.setText("Novo");
        pnlNovo1.add(lblTextNovo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconNovo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifpe/imagens/icon.png"))); // NOI18N
        pnlNovo1.add(lblIconNovo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlNovo1);
        pnlNovo1.setBounds(672, 0, 75, 100);

        pnlAlterar1.setBackground(new java.awt.Color(18, 29, 49));
        pnlAlterar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextAlterar1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextAlterar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextAlterar1.setText("Alterar");
        pnlAlterar1.add(lblTextAlterar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconAlterar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconAlterar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifpe/imagens/icon.png"))); // NOI18N
        pnlAlterar1.add(lblIconAlterar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlAlterar1);
        pnlAlterar1.setBounds(747, 0, 75, 100);

        pnlExcluir1.setBackground(new java.awt.Color(18, 29, 49));
        pnlExcluir1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextExcluir1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextExcluir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextExcluir1.setText("Excluir");
        pnlExcluir1.add(lblTextExcluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconExcluir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifpe/imagens/icon.png"))); // NOI18N
        pnlExcluir1.add(lblIconExcluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlExcluir1);
        pnlExcluir1.setBounds(822, 0, 75, 100);

        pnlRelacao1.setBackground(new java.awt.Color(18, 29, 49));
        pnlRelacao1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextRelacao1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextRelacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextRelacao1.setText("Relação");
        pnlRelacao1.add(lblTextRelacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 75, 30));

        lblIconRelacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconRelacao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifpe/imagens/icon.png"))); // NOI18N
        pnlRelacao1.add(lblIconRelacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 75, 70));

        jPanel2.add(pnlRelacao1);
        pnlRelacao1.setBounds(897, 0, 75, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistematabica/imagens/sistema/icones/logoEsq.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 300, 80);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 100));

        jPanel3.setBackground(new java.awt.Color(18, 29, 49));

        jTable1.setForeground(new java.awt.Color(18, 29, 49));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(18, 29, 49));
        jTable1.setSelectionBackground(new java.awt.Color(18, 29, 49));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 970, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRelacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacaoMouseClicked
        operadorCaixaController.relacao();
    }//GEN-LAST:event_lblRelacaoMouseClicked

    private void lblRelacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacaoMouseEntered
        mouseEntered(pnlRelacao);
    }//GEN-LAST:event_lblRelacaoMouseEntered

    private void lblRelacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacaoMouseExited
        mouseExited(pnlRelacao);
    }//GEN-LAST:event_lblRelacaoMouseExited

    private void lblExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseClicked

        // ser algum dado estiver selecionado na tabela
        if(jTable1.getSelectedRow() != -1) {
           
            // se a remoção do banco de dados foi feita com sucesso
            if(operadorCaixaController.deletarID(operadorCaixaTableModel.getList(jTable1.getSelectedRow()).getDados().getNumeroRegistro())) {
                
                System.out.println( operadorCaixaTableModel.getList(jTable1.getSelectedRow()).getDados().getNomeCompleto() );    
             
                // remover da tabela
                operadorCaixaTableModel.removeRow(jTable1.getSelectedRow());
                
            }else {
                JOptionPane.showMessageDialog(null,"não foi possivel remover do banco de dados");
            }
            
            
        }else if(jTable1.getSelectedRow() == -1){
           // JOptionPane.showMessageDialog(null,"Operador não selecionado");
        }
        
    }//GEN-LAST:event_lblExcluirMouseClicked

    private void lblExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseEntered
        mouseEntered(pnlExcluir);
    }//GEN-LAST:event_lblExcluirMouseEntered

    private void lblExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseExited
        mouseExited(pnlExcluir);
    }//GEN-LAST:event_lblExcluirMouseExited

    private void lblAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseClicked

        // se algum dado estiver selecionado na tabela
        if (jTable1.getSelectedRow() != -1) {
            
            this.dispose();
            operadorCaixaController.telaAlterar(operadorCaixaTableModel.getList(jTable1.getSelectedRow()));

        } else if (jTable1.getSelectedRow() == -1) {
             JOptionPane.showMessageDialog(null,"Operador não selecionado");
        }

        //this.dispose();
        
        //operadorCaixaController.alterar();

    }//GEN-LAST:event_lblAlterarMouseClicked

    private void lblAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseEntered
        mouseEntered(pnlAlterar);
    }//GEN-LAST:event_lblAlterarMouseEntered

    private void lblAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseExited
        mouseExited(pnlAlterar);
    }//GEN-LAST:event_lblAlterarMouseExited

    private void lblNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoMouseClicked
        this.dispose();      
        operadorCaixaController.telaNovo();
    }//GEN-LAST:event_lblNovoMouseClicked

    private void lblNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoMouseEntered
        mouseEntered(pnlNovo);
    }//GEN-LAST:event_lblNovoMouseEntered

    private void lblNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoMouseExited
        mouseExited(pnlNovo);
    }//GEN-LAST:event_lblNovoMouseExited

    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseClicked

        // se algum dado estiver selecionado na tabela
        if (jTable1.getSelectedRow() != -1) {
            
            operadorCaixaController.telaImagem(operadorCaixaTableModel.getList(jTable1.getSelectedRow()).getDados().getURLFoto());
            
        } else if (jTable1.getSelectedRow() == -1) {
             JOptionPane.showMessageDialog(null,"Operador não selecionado");
        }

    }//GEN-LAST:event_lblImagemMouseClicked

    private void lblImagemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseEntered
        mouseEntered(pnlImagem);
    }//GEN-LAST:event_lblImagemMouseEntered

    private void lblImagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseExited
        mouseExited(pnlImagem);
    }//GEN-LAST:event_lblImagemMouseExited

    private void lblAlterar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAlterar1MouseClicked

    private void lblAlterar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAlterar1MouseEntered

    private void lblAlterar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAlterar1MouseExited

    private void lblExcluir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExcluir1MouseClicked

    private void lblExcluir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluir1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExcluir1MouseEntered

    private void lblExcluir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluir1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExcluir1MouseExited

    private void lblNovo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNovo1MouseClicked

    private void lblNovo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNovo1MouseEntered

    private void lblNovo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNovo1MouseExited

    private void lblRelacao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacao1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRelacao1MouseClicked

    private void lblRelacao1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacao1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRelacao1MouseEntered

    private void lblRelacao1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelacao1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRelacao1MouseExited

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        mouseExited(pnlSair);
    }//GEN-LAST:event_lblSairMouseExited

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        mouseEntered(pnlSair);
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
      this.dispose();      
      //operadorCaixaController.sair();
    }//GEN-LAST:event_lblSairMouseClicked


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperadorCaixaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperadorCaixaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperadorCaixaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperadorCaixaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperadorCaixaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAlterar;
    private javax.swing.JLabel lblAlterar1;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblExcluir1;
    private javax.swing.JLabel lblIconAlterar;
    private javax.swing.JLabel lblIconAlterar1;
    private javax.swing.JLabel lblIconExcluir;
    private javax.swing.JLabel lblIconExcluir1;
    private javax.swing.JLabel lblIconImagem;
    private javax.swing.JLabel lblIconNovo;
    private javax.swing.JLabel lblIconNovo1;
    private javax.swing.JLabel lblIconRelacao;
    private javax.swing.JLabel lblIconRelacao1;
    private javax.swing.JLabel lblIconSair;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNovo;
    private javax.swing.JLabel lblNovo1;
    private javax.swing.JLabel lblRelacao;
    private javax.swing.JLabel lblRelacao1;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblTextAlterar;
    private javax.swing.JLabel lblTextAlterar1;
    private javax.swing.JLabel lblTextExcluir;
    private javax.swing.JLabel lblTextExcluir1;
    private javax.swing.JLabel lblTextImagem;
    private javax.swing.JLabel lblTextNovo;
    private javax.swing.JLabel lblTextNovo1;
    private javax.swing.JLabel lblTextRelacao;
    private javax.swing.JLabel lblTextRelacao1;
    private javax.swing.JLabel lblTextSair;
    private javax.swing.JPanel pnlAlterar;
    private javax.swing.JPanel pnlAlterar1;
    private javax.swing.JPanel pnlExcluir;
    private javax.swing.JPanel pnlExcluir1;
    private javax.swing.JPanel pnlImagem;
    private javax.swing.JPanel pnlNovo;
    private javax.swing.JPanel pnlNovo1;
    private javax.swing.JPanel pnlRelacao;
    private javax.swing.JPanel pnlRelacao1;
    private javax.swing.JPanel pnlSair;
    // End of variables declaration//GEN-END:variables
}
